language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - wget https://getcomposer.org/composer.phar
  - php composer.phar install --no-interaction
  - composer self-update
  - git clone https://github.com/octobercms/october.git
  - git clone https://github.com/rainlab/user-plugin.git october/plugins/rainlab/user
  - mkdir -p ./october/plugins/bedard/saas
  - mv !(october) october/plugins/bedard/saas
  - cd october
  - composer install
  - cp config/cms.php config/testing/cms.php
  - cd ./plugins/bedard/saas
  - composer install

script:
  - if [[ $TRAVIS_PHP_VERSION = 7.3 ]]; then php vendor/bin/phpunit --coverage-clover clover.xml; else php vendor/bin/phpunit; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION = 7.3 ]]; then bash <(curl -s https://codecov.io/bash) -v -cF php; fi