version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.3-node
    steps:
      - run:
          name: Clone October
          command: |
            git clone https://github.com/octobercms/october.git
      - run:
          name: Install plugins
          command: |
            git clone https://github.com/scottbedard/oc-stripe-plugin ./october/plugins/bedard/stripe
            git clone https://github.com/rainlab/user-plugin.git ./october/plugins/rainlab/user
      - restore_cache:
          key: -v3-{{ checksum "october/composer.json" }}-{{ checksum "october/plugins/bedard/stripe/composer.lock" }}
      - run:
          name: Install dependencies
          command: |
            (cd ./october && composer install)
            (cd ./october/plugins/bedard/stripe && composer install)
      - save_cache:
          key: -v3-{{ checksum "october/composer.json" }}-{{ checksum "october/plugins/bedard/stripe/composer.lock" }}
          paths:
            - "october/vendor"
            - "october/plugins/bedard/stripe/vendor"
      - run:
          name: Configure environment
          command: |
            printf "STRIPE_KEY=$STRIPE_KEY\nSTRIPE_SECRET=$STRIPE_SECRET" > "./october/.env"
      - run:
          name: Test
          command: |
            cd ./october/plugins/bedard/stripe
            phpdbg -qrr vendor/bin/phpunit -d memory_limit=512M --coverage-clover clover.xml
      - run:
          name: Codecov
          command: |
            cd ./october/plugins/bedard/stripe
            bash <(curl -s https://codecov.io/bash) -v -cF php
workflows:
  version: 2
  tests:
    jobs:
      - test