# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    has_active_plan:
        default: 0
        label: bedard.saas::lang.schedules.list.has_active_plan_filter
        scope: hasActivePlan
        type: checkbox