# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.saas::lang.schedules.model

# Model Form Field configuration
form: $/bedard/saas/models/schedule/fields.yaml

# Model Class name
modelClass: Bedard\Saas\Models\Schedule

# Default redirect location
defaultRedirect: bedard/saas/schedules

# Create page
create:
    title: backend::lang.form.create_title
    redirect: bedard/saas/schedules/update/:id
    redirectClose: bedard/saas/schedules

# Update page
update:
    title: backend::lang.form.update_title
    redirect: bedard/saas/schedules
    redirectClose: bedard/saas/schedules

# Preview page
preview:
    title: backend::lang.form.preview_title
