# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.saas::lang.coupons.model

# Model Form Field configuration
form: $/bedard/saas/models/coupon/fields.yaml

# Model Class name
modelClass: Model

# Default redirect location
defaultRedirect: bedard/saas/coupons

# Create page
create:
    title: backend::lang.form.create_title
    redirect: bedard/saas/coupons/update/:id
    redirectClose: bedard/saas/coupons

# Update page
update:
    title: backend::lang.form.update_title
    redirect: bedard/saas/coupons
    redirectClose: bedard/saas/coupons

# Preview page
preview:
    title: backend::lang.form.preview_title
