# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.saas::lang.products.model

# Model Form Field configuration
form: $/bedard/saas/models/product/fields.yaml

# Model Class name
modelClass: Bedard\Saas\Models\Product

# Default redirect location
defaultRedirect: bedard/saas/products

# Create page
create:
    title: backend::lang.form.create_title
    redirect: bedard/saas/products/update/:id
    redirectClose: bedard/saas/products

# Update page
update:
    title: backend::lang.form.update_title
    redirect: bedard/saas/products
    redirectClose: bedard/saas/products

# Preview page
preview:
    title: backend::lang.form.preview_title
