# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    is_active:
        default: false
        label: bedard.saas::lang.products.list.is_active_filter
        scope: active
        type: checkbox