# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.saas::lang.plans.model

# Model Form Field configuration
form: $/bedard/saas/models/plan/fields.yaml

# Model Class name
modelClass: Bedard\Saas\Models\Plan

# Default redirect location
defaultRedirect: bedard/saas/plans

# Create page
create:
    title: backend::lang.form.create_title
    redirect: bedard/saas/plans/update/:id
    redirectClose: bedard/saas/plans

# Update page
update:
    title: backend::lang.form.update_title
    redirect: bedard/saas/plans
    redirectClose: bedard/saas/plans

# Preview page
preview:
    title: backend::lang.form.preview_title
